### ISSUE TITLE
Un-inert doesn't remove tabindex=-1 if inert was applied to elements, which was selected by *

### ISSUE THREAD

**Issue by archual** [WICG/inert#118]
I tried to apply inert attribute to all child elements of certain node, using selector like '.main *'. it adds inert attribute to all elements in dome under .main node, also this adds tabindex and aria-hidden. But when I remove inert by using selector '*[inert]' and  removeAttribure - inert and aria-hidden attribute are removed, but tabindex keeps in elements, and elements can't be focused.

All works if I use specific selector like '.main span' or '.main .links'.
Looks like * selector broke inert polyfill or it can't work with elements, which was getting bu such selector.

**Comment by robdodson** [comment]
ok I'll close this issue then. Let us know if you still have problems :)
