### ISSUE TITLE
Does not bundle correctly when using Rollup

### ISSUE THREAD

**Issue by mi-ztroh** [WICG/inert#132]
See output below.  Linking to a similar issue in another project that was recently solved.

https://github.com/material-components/material-components-web-components/issues/257

![image](https://user-images.githubusercontent.com/52385193/64227427-0b8b8a80-cea9-11e9-95ed-7069f6b27e9a.png)

**Comment by robdodson** [comment]
Replied in the thread you linked to.

**Comment by mi-ztroh** [comment]
Confirmed the new version works for me.  Thanks for the quick turnaround!
