### ISSUE TITLE
Details tag becomes focusable even after applying inert

### ISSUE THREAD

**Issue by pranav300** [WICG/inert#133]
After applying inert to the root element while opening an overlay. The `details` tag which is a child element of root is still focusable. This causes an axe-core violation. Is there a way to make details tag not focusable? 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/29273628/64231538-8dad9a80-cf0d-11e9-9397-e341bfe381cb.gif)

**Comment by robdodson** [comment]
Hi @pranav300, it's a little hard for me to read what's going on in that video. Are you able to share a live URL example that I can take a look at?

**Comment by pranav300** [comment]
You can look into this link [terra-ui.com](https://engineering.cerner.com/terra-ui/components/terra-dialog-modal/dialog-modal/dialog-modal).
## Steps to Reproduce


1. On the link above click on the button on the first example.
2. then run axe-core on the page
3. the details tag which is the child of root element will be focusable but the inert has been applied on the root element.

**Comment by bjankord** [comment]
@robdodson I've created a reduced test case of what we're seeing:
https://codepen.io/bjankord/pen/YzKYqam

The details element nested within a div with the inert attribute is still interactive.

**Comment by bjankord** [comment]
In my quick testing, I haven't found a way to remove the details/summary from the tab order. This may be a browser limitation? Applying `tabindex="-1"` to both the details and summary element seems to have no effect on tab order, I am able to press tab key and shift focus to the details element. Curious what your thoughts are on this @robdodson

**Comment by robdodson** [comment]
ok I think you've hit a bug in the polyfill.

If you get rid of the inert polyfill and put `tabindex=-1` on the `summary` element, it seems to behave as expected.

However, if you're using the inert polyfill and you do something like `<summary inert tabindex="-1">` it will remove the `tabindex="-1"`.

@alice do you think the inert tree walker could add tabindex=-1 to summary elements when it's walking the tree?
