### ISSUE TITLE
Question: HTMLElement or Element

### ISSUE THREAD

**Issue by JakeChampion** [WICG/inert#143]
I couldn't get an answer to this question from the specification because the specification:
>does not define or create any content attribute named "inert"

Should the attribute live on HTMLElement.prototype or Element.prototype?

MDN documentation states HTMLElement but this polyfill attaches it to Element.prototype

MDN: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement
<img width="667" alt="image" src="https://user-images.githubusercontent.com/1569131/70545175-123f3300-1b65-11ea-848b-77739191c4cc.png">

This polyfill: https://github.com/WICG/inert/blob/6eb51778ab647783f034f7b4959f407b93c1ce85/src/inert.js#L720-L721

**Comment by alice** [comment]
Apologies; I just updated the README to point the "spec" link to this: https://whatpr.org/html/4288/interaction.html#the-inert-attribute

This defines the `inert` attribute on all Elements.
