### ISSUE TITLE
Injecting inline style violates strict style csp

### ISSUE THREAD

**Issue by WimValgaeren** [WICG/inert#146]
The insertion of the inline style#inert-style tag violates the style-src rule if 'unsafe inline' is not allowed by the csp headers (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src)

Would it be possible to add an option to include the styling as a separate css file?

**Comment by robdodson** [comment]
that seems reasonable. would you be able to submit a PR with that feature?

**Comment by robdodson** [comment]
I believe this is fixed by https://github.com/WICG/inert/pull/148
