### ISSUE TITLE
Unknown Syntax error in IE

### ISSUE THREAD

**Issue by goatandsheep** [WICG/inert#149]
On page loading, I get a Syntax error in IE that points to the `InertRoot` class. On FF and Chrome it seems okay. We are using Babel and our application has been IE compliant so far. I'm not sure what to make of the error:
![image](https://user-images.githubusercontent.com/5570628/80606293-24314d80-8a02-11ea-8992-e66ec2cca001.png)

![image](https://user-images.githubusercontent.com/5570628/80606317-2dbab580-8a02-11ea-9891-b82e5a780e8b.png)

To add further details, we are using jquery.

**Comment by r0mflip** [comment]
From the images it look like your insert is not transpiled for IE compat. Try transpiling it or you can have a try using https://unpkg.com/wicg-inert

**Comment by goatandsheep** [comment]
Oh this is a duplicate of #136 then I think

**Comment by goatandsheep** [comment]
How do I import a specific version, i.e. `main` vs `module`?

I'm doing this: `import "wicg-inert";`

**Comment by goatandsheep** [comment]
I found [this example webpack.config.js](https://github.com/uprtcl/intercreativity-app/blob/master/webpack.config.js), which does:

```javascript
module.exports = {
  resolve: {
    alias: {
      'wicg-inert': path.resolve('./node_modules/wicg-inert/dist/inert'),
    }
  }
}
```
