### ISSUE TITLE
Is inert string or boolean?

### ISSUE THREAD

**Issue by goatandsheep** [WICG/inert#150]
I noticed that this library is checking for [existence of inert](https://github.com/WICG/inert/blob/03f32ca293c33cdbfa469535eae367b5d69b5ae5/src/inert.js#L185), i.e. boolean or `true` / `false`, whereas [this documentation on MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert) uses string, i.e. `"true"` / `"false"`. Which is it?

**Comment by saschanaz** [comment]
HTML attributes (`<div inert="true">`)are all string, while IDL attribute (`div.inert = true`) can be boolean. Thus, it's both.

**Comment by alice** [comment]
Looks like the MDN documentation is inaccurate - the [spec PR](https://whatpr.org/html/4288/bcd5d61...f538a12/interaction.html#the-inert-attribute) specifies it as a boolean attribute.

**Comment by goatandsheep** [comment]
@saschanaz no not all HTML attributes are strong. `disabled` is`boolean`

**Comment by goatandsheep** [comment]
@alice thank you! I have since fixed the MDN article
