### ISSUE TITLE
License for NPM wicg/inert

### ISSUE THREAD

**Issue by kensgists** [WICG/inert#168]
Our organization has policies that prevent us from consuming into our secured repository any code that is not accompanied by a license. 

Could you please include a license for [wicg-inert?](https://www.npmjs.com/package/wicg-inert)

**Comment by benlangfeld** [comment]
There's already a PR ready for this, the maintainers just need to merge and release.

https://github.com/WICG/inert/pull/171

**Comment by kensgists** [comment]
@benlangfeld, thanks for the work on this. I see @robdodson mentions there is a hold up around which license to support?

Is there a ETA for getting the licensing in NPMJS?

**Comment by benlangfeld** [comment]
@kensgists I updated https://github.com/WICG/inert/pull/171 with my thoughts.

**Comment by bkardell** [comment]
Closing this as 171 is merged
