### ISSUE TITLE
 W3C Software and Document License (2015/05/13) was expired

### ISSUE THREAD

**Issue by nissy-dev** [WICG/inert#196]
The license of this package is specified to W3C Software and Document License (2015/05/13) , but it was expired in 2022.
https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document

We can use this package under the new W3C Software and Document License (2023/01/01)?

**Comment by robdodson** [comment]
@marcoscaceres do you know if we need to swap the LICENSE.md to a different one?

**Comment by marcoscaceres** [comment]
I think you just need to point to this one now:
https://www.w3.org/Consortium/Legal/2023/software-license.html

**Comment by bkardell** [comment]
Updated
