### ISSUE TITLE
Malicious behavior detected in wicg-inert-3.1.2 package

### ISSUE THREAD

**Issue by rupeshdeotale97** [WICG/inert#198]
This package has been identified by Mend as containing potential malicious functionality. The severity of the functionality can change depending on where the library is running (user's machine or backend server). The following risks were identified: Malware dropper – this package contains a Trojan horse, allowing the unauthorized installation of other potentially malicious software.

Similar issue reported Over [wicg-inert-3.1.2 package](https://github.com/carbon-design-system/carbon-charts/issues/1865)

**Comment by jlczuk** [comment]
Someone created [PR-197](https://github.com/WICG/inert/pull/197) to address this.

Mend identified this package as being vulnerable because it refers to the old polyfill.io domain, which should no longer be used or referred to.

**Comment by VikrantSangwan** [comment]
Is this issue resolved I could see the pr (mentioned above) is still in the open state, Should we switch to the wicg-inert-3.1.1 package till this issue persists?

**Comment by Eric-Arellano** [comment]
> Is this issue resolved

It will not be resolved until https://github.com/WICG/inert/pull/197 is merged and the package is re-released with 3.1.1.

**Comment by bkardell** [comment]
Merged, but just to note:  It's a bit of the documentation that had some outdated advice though, not the package/code itself that was problematic.

**Comment by CeceliaYu** [comment]
the PR is merged, can you release new version?

**Comment by rupeshdeotale97** [comment]
@bkardell  Could you please release the new version so, that we can close Mend critical finding

**Comment by rupeshdeotale97** [comment]
@bkardell Any plan to release this change in 3.1.3

**Comment by jlczuk** [comment]
It would have been nice to remove references to polyfill.io from the README.md and karma.conf.js files too.

**Comment by ForkInSpace** [comment]
@bkardell Can this now be released on NPM ?
