### ISSUE TITLE
Request to publish v3.1.3 to npm repo

### ISSUE THREAD

**Issue by CeceliaYu** [WICG/inert#200]
3.1.3 is listed here https://github.com/WICG/inert/releases:
<img width="1140" alt="image" src="https://github.com/user-attachments/assets/64dfb5ab-ab1b-4617-ac00-eb12798d7241">

while I can't get it from npm repository: https://www.npmjs.com/package/wicg-inert
<img width="1204" alt="image" src="https://github.com/user-attachments/assets/80bcf7d8-1624-4ca7-abba-f5e4df34de6d">

can someone help to publish v3.1.3?

**Comment by ForkInSpace** [comment]
This is needed yesterday.
This version needs to be released on npm registry so that private artifactories can pick it up and make it available within orgs (like in my case). 

Somebody please action this.

**Comment by ForkInSpace** [comment]
@bkardell

**Comment by CeceliaYu** [comment]
@robdodson anything you can help with here?

**Comment by robdodson** [comment]
> This is needed yesterday.

@ForkInSpace comments like this aren't helpful

> @robdodson anything you can help with here?

@CeceliaYu yes I'll try to take a look at this today

**Comment by robdodson** [comment]
3.1.3 should be up on npm now. Sorry for the delay on this folks
