### ISSUE TITLE
support for IE and Safari?

### ISSUE THREAD

**Issue by valdrinkoshi** [WICG/inert#28]
Is it planned to support these browsers?

**Comment by robdodson** [comment]
oh darn it. I thought this had already been merged: https://github.com/WICG/inert/pull/24

We need to transpile to support those browsers

**Comment by valdrinkoshi** [comment]
Oh I see..that PR has some merge conflicts so can't be merged :x

**Comment by robdodson** [comment]
Just merged in 24 which provides a dist version

**Comment by valdrinkoshi** [comment]
\o/
