### ISSUE TITLE
`Let` not yet supported in strict mode in Safari 9

### ISSUE THREAD

**Issue by marcysutton** [WICG/inert#37]
I'm getting an error in Safari 9.1.1 when I include the inert.js file. I want to test dialogs with Voiceover, which is how I ran into this issue. 

Here's the error:
```
inert.js:93 
SyntaxError: Unexpected use of reserved word 'let' in strict mode
```

I saw some stuff in another issue about transpiling for other browsers. Do I need to do anything special with the polyfill to get it to work with Safari?

Thanks 😺

**Comment by valdrinkoshi** [comment]
Are you using the `dist/` version of the polyfill? https://github.com/WICG/inert/blob/master/dist/inert.js

**Comment by marcysutton** [comment]
Awe, nope. I used the `inert.js` file. Wish I'd realized that before I recorded it in a screencast.

**Comment by alice** [comment]
Ah - yeah, we should put the es6 source into a `src` directory, most likely - I'm sure other people will get bitten by this.

**Comment by robdodson** [comment]
Yep working on it

**Comment by marcysutton** [comment]
Sounds like there are some changes to the structure, I'm going to close this! Thanks everyone
