### ISSUE TITLE
inert polyfill breaks build processes that use phantomJs

### ISSUE THREAD

**Issue by shreya-work** [WICG/inert#41]
```
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: Map
  at /Users/runtimeZero/code/app/client/vendor/inert/inert.min.js:589

```

The use of Map doesnt go well with PhantomJS. Is there any solution available for this ?

**Comment by jdan** [comment]
Hey @shreya-work,

This polyfill will only work in browsers that support [the `Map` constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map). If you want to use it with an older JavaScript runtime you'll need to include a separate polyfill for Map, such as [babel-polyfill](https://babeljs.io/docs/usage/polyfill/).

[As suggested on StackOverflow](http://stackoverflow.com/a/40388592/712889), try adding the following to the document in your build process:

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.16.0/polyfill.min.js"></script>
```

**Comment by robdodson** [comment]
Thanks @jdan, I was just discussing this same approach with @alice. I'll add an update to the README to make note of this polyfill

**Comment by shreya-work** [comment]
Thanks @jdan for the response.
I tried adding the Map polyfill to the build  but for some reason PhantomJs still complains..
Any chances we can have this polyfill without ES6 constructs ?

**Comment by robdodson** [comment]
What errors does it throw after you add the polyfills?
