### ISSUE TITLE
Exception in Edge: Object doesn't support property or method 'matches'

### ISSUE THREAD

**Issue by vcorr** [WICG/inert#51]
I keep getting this exception in Edge, line inert.js (174,9) - this happens also in the demo page and the checkboxes don't seem to work.

OS: Windows 10, 
Browser:Microsoft Edge 38.14393.0.0

**Comment by robdodson** [comment]
can you share the exception?

**Comment by valdrinkoshi** [comment]
In IE/Edge `matches` is supported, but with `-ms` prefix http://caniuse.com/#search=matches

**Comment by vcorr** [comment]
@robdodson  

```
SCRIPT438: Object doesn't support property or method 'matches'
inert.js (737,15)
```

**Comment by vcorr** [comment]
I made a fork with a quick and dirty fix based on https://davidwalsh.name/element-matches-selector, basically just substituted the .matches with
 ```
function matchSelector(node, selector) {
         let func = node.matches || node.msMatchesSelector;
         return func.call(node,selector);
 }

```
Seems to work according to your test page
