### ISSUE TITLE
IE10 issues

### ISSUE THREAD

**Issue by lmounsey** [WICG/inert#55]
Hi there

I've come across a couple issues when testing in IE10

When making the subtree unfocusable, it throws an error on some HTML tags as it doesn't support the contains method. Those objects being SVGs and comments.

I've just made a workaround (not that nice) to test for invalid tags. 

```
var invalidTags = ['undefined', 'svg'];

if (!invalidTags.indexOf(startNode.tagName)) {
     if (startNode.contains(activeElement)) activeElement.blur();
}
```

Also, IE10 doesn't support pointer-events - I've had to use Modernizr to test for pointer events, then add a class if not supported so it adds visibility:hidden to inert elements. As I typically use inert for off-page/hidden objects, it's worked OK for me.

**Comment by robdodson** [comment]
bummer about the IE10 issues.

@alice what are your thoughts here? I can increase the test matrix to include IE10 I think, but we'll need to add some hackery. Just wondering if we want to have a browser support cut off somewhere? Like IE10+ ? ¯\_(ツ)_/¯

**Comment by bjankord** [comment]
IE10+ would be awesome.

**Comment by JakeChampion** [comment]
You could use this polyfill in combination with https://polyfill.io/v3/polyfill.js?features=Node.prototype.contains to ensure it works in IE 10 :-)

**Comment by robdodson** [comment]
oh yeah thank you @JakeChampion! I forgot we have a section in the readme about this: https://github.com/WICG/inert#legacy-browser-support

I think for now we'll keep the test matrix as it is because SauceLabs is already flaky enough with our current list of browsers (IE bombs out a lot)
