### ISSUE TITLE
Add minified build to dist

### ISSUE THREAD

**Issue by garrettjohnston** [WICG/inert#56]
Hi,

Could you please rebuild with the minified version of inert in the dist? Some packages have dependencies on the minified build that I cannot change.

Thanks!

**Comment by robdodson** [comment]
oh ok. Sorry about that, we weren't sure if folks were using it. I'll ping this thread when I've got it in there.

**Comment by robdodson** [comment]
ok just published a new version. Should be good to go.

**Comment by garrettjohnston** [comment]
Thanks Rob!
