### ISSUE TITLE
React doesn't play nice with inert property

### ISSUE THREAD

**Issue by robdodson** [WICG/inert#58]
Example: https://www.webpackbin.com/bins/-KmmTaOzo6tSQqTeIv2H

React will ignore attempts to set the `inert` prop because it doesn't allow setting non-standard or experimental props on a node. https://facebook.github.io/react/warnings/unknown-prop.html

The workaround is to use the node's ref to set the inert attribute instead.
``` js
return <div ref={node => node && node.setAttribute('inert', '')} />
```

**Comment by robdodson** [comment]
Closing this as it's a React specific issue and I just wanted to document the workaround. You can see the discussion on React allowing custom attributes/properties here: https://github.com/facebook/react/issues/140

**Comment by pimterry** [comment]
Just to extend this a little, if you want _conditional_ inertness in React you need something more like:

```
<div
  ref={node => node && (shouldBeInert ?
    node.setAttribute('inert', '') : node.removeAttribute('inert')
  )}
/>
```

**Comment by robdodson** [comment]
Thank you Tim!

**Comment by maracuja-juice** [comment]
I am receiving `node.setAttribute is not a function` when I try to use this. Any idea on how to solve this?

**Comment by bkardell** [comment]
@maracuja-juice you're getting this following @robdodson's example ?

hey @robdodson - the link above showing a functional snip at  https://www.webpackbin.com/bins/-KmmTaOzo6tSQqTeIv2H appears to be gone

**Comment by maracuja-juice** [comment]
@bkardell I'm using pimterry's example but I guess I will have the exact same behaviour if I would use the original suggestion as they're not that different.

**Comment by bkardell** [comment]
Can you share any running code? Can you add a debugger and see what node is there?

**Comment by robdodson** [comment]
Hm this sounds like an issue with how @maracuja-juice is using refs in React. I'm not super familiar with React but maybe in newer versions the ref syntax has changed?

**Comment by defnotrobbie** [comment]
i'd just like to add that the following works for both adding and removing `inert` in React without using refs or DOM methods. note that the true assignment is empty string and the false assignment is `null`. the true assignment can be any string as far as i can tell. the false assignment can be `null`, `undefined`, or `false`.
```jsx
<div inert={inertCondition ? '' : null} />
```

**Comment by mvoloskov** [comment]
If you're by any chance using React with TypeScript and [Linaria](https://github.com/callstack/linaria), do this:
```
const InertElement = styled.div<{ inert?: string | null }>`
   /* your styles here */
`
```

Then, as @defnotrobbie suggested, you can use inert conditionally, and TypeScript will still be happy because we defined an additional prop:

```
<InertElement inert={inertCondition ? '' : null} />
```

You can also do it in plain React with TypeScript:
```
import { HTMLProps, FC } from 'react'

interface Props extends HTMLProps<HTMLDivElement> {
   inert?: string | null
}

const InertDiv: FC<Props> = props => <div {...props} />
```

**Comment by LarsEjaas** [comment]
If anyone needs a workaround until this is implemented I have solved it like this:

```
<div inert={disabled? "" : undefined}
```
inert undefined will not pass inert to the underlying DOM element and inert="" will pass to the DOM node and works like inert={true}

then: 
```
declare global {
//TODO: remove this when inert is supported in React types
  namespace JSX {
    interface IntrinsicAttributes {
      inert?: "";
    }
  }
}
```

**Comment by yangshun** [comment]
Declaring on `namespace JSX` did not work for me, but this did:

```ts
declare module 'react' {
  interface HTMLAttributes<T> extends DOMAttributes<T> {
    /**
     * Boolean attribute indicating that the browser will ignore the element.
     *
     * @see {@link https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert MDN Web Docs}
     */
    inert?: '';
  }
}
```
