### ISSUE TITLE
Inerting element in shadow DOM throws error

### ISSUE THREAD

**Issue by straker** [WICG/inert#62]
If you try to inert an element in a shadow root, inert.js throws an error when trying to get the `root.activeElement` and pass it to `compareDocumentPosition`.

```js
let div = document.createElement('div');
let shadow = div.attachShadow({mode: 'open'});
shadow.innerHTML = '<button>btn 1</button><button>btn 2</button>'

shadow.querySelector('button').inert = true 

/*
inert.js:73 Uncaught TypeError: Failed to execute 'compareDocumentPosition' on 'Node': parameter 1 is not of type 'Node'.
    at contains (inert.js:73)
    at InertRoot._makeSubtreeUnfocusable (inert.js:250)
    at new InertRoot (inert.js:162)
    at InertManager.setInert (inert.js:717)
    at HTMLButtonElement.set$$1 [as inert] (inert.js:1020)
    at <anonymous>:1:38
*/
```

**Comment by bkardell** [comment]
hmm... the active element winds up being null in https://github.com/WICG/inert/blob/master/dist/inert.js#L251

should default it to root?

**Comment by valdrinkoshi** [comment]
This seems more a bug of `node-contains`, as the native Node.contains accepts `undefined` or `null` as parameter (e.g. `document.body.contains(undefined)`

**Comment by straker** [comment]
So should the contains polyfill just return false if `other` is falsey?

```js
return other && (node === other || !!(node.compareDocumentPosition(other) & 16) )
```

**Comment by valdrinkoshi** [comment]
Yeah something on those lines

**Comment by LouisStAmour** [comment]
It’s actually not a node-contains bug because it’s a precondition error if null is passed in to contains, at least according to a Firefox bug report I saw. You need a try catch or you need to check first. My fix mentioned in #64 is correct.

**Comment by LouisStAmour** [comment]
Never mind, I just read the spec. Indeed it’s supposed to always return false. My mistake

**Comment by straker** [comment]
So we're going on a week now and I haven't heard from the creator of node-contains about the pr. It hasn't been updated in 3 years, should it's code just be consumed and updated?

**Comment by robdodson** [comment]
yeah probably, looks simple enough
