### ISSUE TITLE
Removing inert does not maintain elements previous aria-hidden state

### ISSUE THREAD

**Issue by straker** [WICG/inert#67]
If this is the element to inert 

```
<button aria-hidden=true>Click</button>
```

When you inert the element and then remove the inert attribute, the `aria-hidden` attribute is also removed. 

The `aria-hidden` state should probably be saved just like the `tabindex` so it can be properly restored.

**Comment by bkardell** [comment]
ouch. good catch.  interested in sending a pull?

**Comment by straker** [comment]
Can do

**Comment by alice** [comment]
+1 good catch!
