### ISSUE TITLE
Array.from present in umd build of inert.js

### ISSUE THREAD

**Issue by morsmodr** [WICG/inert#70]
Hi,

**Bug report**

Using the umd build (from dist) of inert.js breaks in IE11 as IE11 doesn't support Array.from. However, in the first place, I would expect the umd build to be es5 compliant.

Looks like babel-polyfill doesn't extend the Array class
http://babeljs.io/docs/usage/caveats/#polyfills and will need [babel-plugin-transform-builtin-extend](https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend) to do that.

![image](https://user-images.githubusercontent.com/7231256/31290369-db06892e-aa91-11e7-8690-20601184b0cb.png)

![image](https://user-images.githubusercontent.com/7231256/31290398-ee1894e4-aa91-11e7-839f-e8e691b58e8a.png)

**Comment by morsmodr** [comment]
The example page https://wicg.github.io/inert/index.html also breaks on IE 11

**Comment by robdodson** [comment]
Good catch. We can probably work around this using the [].slice trick

**Comment by robdodson** [comment]
Fixed (ca1d7f71b995c4059a0d9663291a25ec76510697) and updated on npm

**Comment by joe-watkins** [comment]
HI Rob! Is the demo calling that right `dist` file? It is calling a version that has `array.from` in it still.

From demo page: 
https://wicg.github.io/inert/index.html

``` html
<script src="dist/inert.js"></script>
```

https://wicg.github.io/inert/dist/inert.js

**Comment by robdodson** [comment]
oh i can fix that. I think that whole demo page is outdated tbh. It's a stale publish to gh-pages I think.

**Comment by joe-watkins** [comment]
@robdodson tnx! Side note - I was all excited to employ this polyfill for a large client and had to yank it due to IE bugs and a babel.js polyfill dependency. I wish this thing reached more because it totally rocks!

**Comment by robdodson** [comment]
Which IE bugs did you encounter?
Also, why was the babel polyfill an issue? I believe you should be able to feature detect it so it only gets included in IE pages?

**Comment by joe-watkins** [comment]
Howdy @robdodson  :)

First ran into the array.from() bug in this issue, which appears to be fixed with your `splice` approach. So moved to the more recent umd build and then ran into a `Symbol.iterator` bug. Looks like IE doesn't play with that either.

The client wasn't into adding another 100k for babel's polyfill -- even conditionally. 

Would you like me to create an issue for the IE `Symbol.iterator` bug?

**Comment by robdodson** [comment]
yep, thank you :)

**Comment by robdodson** [comment]
Digging into this a bit more, it definitely looks like the polyfill is busted in IE. I've been meaning to revamp the tests for it like we did for focus-visible. Will have to dedicate some time to that soon :\  @alice fyi.
