### ISSUE TITLE
Please add license file and contributing file

### ISSUE THREAD

**Issue by carmacleod** [WICG/inert#73]
To help avoid IP and code provenance issues, please consider adding in a contributor agreement / CLA. This will help consumers that have more rigid IP policies for consuming third-party libraries - like the Eclipse foundation for example.

It could be as simple as adding the contributing.md file in the root of the repo with the following content:

> A CLA is a document that specifies how a project is allowed to use your code. We want a CLA that is simple and as clear as possible so that it doesn't disrupt contributions.
> When you make a contribution to the project, you agree:
> 
> The code you wrote is your original work (you own the copyright) or you otherwise have the right to submit the work.
> You grant the project a nonexclusive, irrevocable license to use your submitted code in any way.
> You are capable of granting these rights for the contribution.
> By submitting a fix you agree to the above statements.

It would also be useful to have a license (or license.md) file so that folks don't need to search the repo to find the license.

**Comment by robdodson** [comment]
Should be fixed now
