### ISSUE TITLE
Any reports of IE11 dying unexpectedly?

### ISSUE THREAD

**Issue by tiandavis** [WICG/inert#81]
Hey Folks!

Love the library and a11ycasts, quick question, "Any reports of IE11 dying unexpectedly?" And by dying, I mean not being able to hit breakpoints or logs at all, just dies. Was hoping to submit a PR, but nothing is really [standing out](https://github.com/WICG/inert/blob/master/src/inert.js#L363) as an issue. Any insider clues?

High-level, basically working through accessible modal dialogs as taught by Rob in this episode of a11ycasts:
https://www.youtube.com/watch?v=JS68faEUduk

The `inert` library worked out really well, just this one scenario where it's failing for IE11 customers while closing one type of modal we have. The library works fine for another type of modal we have, so I'm aware maybe we have some CSS property (or combination of properties) or maybe some HTML layout/attribute that's causing a critical failure in the IE11 rendering engine/MutationObserver event handler. 

We're not "dead in the water" or anything because I was able to replicate the core library function. The replication is good enough atm, but would ideally like to continue using `inert` because of its collective polish. Any thoughts on where I should focus in the inert library? Any IE11 reports that might jog a memory or two? 

Accessibility lawsuits are heating up and on the radar for major web-based products (including ours), so Thanks for advancing accessibility efforts and Keep up the good work!

**Comment by robdodson** [comment]
Possibly related to https://github.com/WICG/inert/issues/75.

You might also check that the console isn't logging any SyntaxErrors. If so then it would stop parsing the file and that might explain why breakpoints wouldn't work.

**Comment by tiandavis** [comment]
Thanks Rob! Will keep digging!

**Comment by tiandavis** [comment]
Will close this issue for now @robdodson, but feel free to reopen as needed and Thanks!
