### ISSUE TITLE
<input type="time"> unresponsive in Firefox after it was temporarily made inert

### ISSUE THREAD

**Issue by rodneyrehm** [WICG/inert#88]
See http://jsbin.com/kexohazifa/edit?html,js,output for a reduced test case.

As soon as the inert attribute is added and removed from `<input type="time">` that element cannot be interacted with anymore.

**Comment by robdodson** [comment]
good catch! I've been meaning to go back and redo the automated tests for inert. I'll add this to the list. Sorry for not showing inert more love, I'm currently 110% focused on landing :focus-visible in Chrome

**Comment by rodneyrehm** [comment]
I've tracked down the problem and reported: https://bugzilla.mozilla.org/show_bug.cgi?id=1451054

Since the wicg-inert polyfill restores the originally set tabindex value, the workaround for this problem is to add `tabindex="0"` to your `<input type="time">`.

I'm closing this because wicg-inert is not at fault here and probably shouldn't have to worry about this bug in Firefox…

**Comment by robdodson** [comment]
Good to know, and thank you for looking into this!
