### ISSUE TITLE
ship as ES6 module?

### ISSUE THREAD

**Issue by valdrinkoshi** [WICG/inert#90]
`src/inert.js` could be used as ES6 module if it wasn't for https://github.com/necolas/dom-matches/issues/3
Would you consider implementing that polyfill instead of having it as a dev dependency?

**Comment by robdodson** [comment]
Our plan is to remove it entirely and tell folks if they need it to use polyfill.io. I just haven't had a chance to work on it :\

**Comment by valdrinkoshi** [comment]
@robdodson can we haz a release? :3

**Comment by robdodson** [comment]
Let me spend some time on this today to see if we can do a release. I'm
holding off only because it would be a major version change since we
removed that polyfill, and if we're doing that I want to make sure to
include any other breaking things we've been holding off on.
